### ISSUE TITLE
请问大神这个问题怎么解决：ModuleNotFoundError: No module named 'lvdm'

### ISSUE THREAD

**Issue by zhaowtVincent** [chaojie/ComfyUI-DynamiCrafter#1]
#read_workflow_json_files_all K:\software\ComfyU\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes\app\
got prompt
[rgthree] Using rgthree's optimized recursive execution.
[rgthree] First run patching recursive_output_delete_if_changed and recursive_will_execute.
[rgthree] Note: If execution seems broken due to forward ComfyUI changes, you can disable the optimization from rgthree settings in ComfyUI.
Prompt executor has been patched by Job Iterator!
2024-02-06 20:39:22,614 - mainlogger - INFO - LatentVisualDiffusion: Running in v-prediction mode
2024-02-06 20:39:22,626 - root - ERROR - !!! Exception during processing !!!
2024-02-06 20:39:22,630 - root - ERROR - Traceback (most recent call last):
  File "K:\software\ComfyU\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\software\ComfyU\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\software\ComfyU\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\software\ComfyU\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DynamiCrafter\nodes.py", line 23, in run_inference
    image2video = Image2Video('./tmp/', resolution=resolution)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\software\ComfyU\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DynamiCrafter\scripts\gradio\i2v_test.py", line 32, in __init__
    model = instantiate_from_config(model_config)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\software\ComfyU\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DynamiCrafter\utils\utils.py", line 34, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\software\ComfyU\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts\..\..\custom_nodes\ComfyUI-DynamiCrafter\lvdm\models\ddpm3d.py", line 680, in __init__
    super().__init__(*args, **kwargs)
  File "K:\software\ComfyU\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts\..\..\custom_nodes\ComfyUI-DynamiCrafter\lvdm\models\ddpm3d.py", line 388, in __init__
    super().__init__(conditioning_key=conditioning_key, *args, **kwargs)
  File "K:\software\ComfyU\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts\..\..\custom_nodes\ComfyUI-DynamiCrafter\lvdm\models\ddpm3d.py", line 82, in __init__
    self.model = DiffusionWrapper(unet_config, conditioning_key)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\software\ComfyU\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts\..\..\custom_nodes\ComfyUI-DynamiCrafter\lvdm\models\ddpm3d.py", line 696, in __init__
    self.diffusion_model = instantiate_from_config(diff_model_config)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\software\ComfyU\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts\..\..\custom_nodes\ComfyUI-DynamiCrafter\utils\utils.py", line 34, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\software\ComfyU\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts\..\..\custom_nodes\ComfyUI-DynamiCrafter\utils\utils.py", line 42, in get_obj_from_str
    return getattr(importlib.import_module(module, package=None), cls)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "K:\software\ComfyU\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts\..\..\custom_nodes\ComfyUI-DynamiCrafter\lvdm\modules\networks\openaimodel3d.py", line 7, in <module>
    from lvdm.models.utils_diffusion import timestep_embedding
ModuleNotFoundError: No module named 'lvdm'

Prompt executed in 0.11 seconds
got prompt
[rgthree] Using rgthree's optimized recursive execution.
Prompt executor has been patched by Job Iterator!
2024-02-06 20:39:37,264 - mainlogger - INFO - LatentVisualDiffusion: Running in v-prediction mode
2024-02-06 20:39:37,272 - root - ERROR - !!! Exception during processing !!!
2024-02-06 20:39:37,274 - root - ERROR - Traceback (most recent call last):
  File "K:\software\ComfyU\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\software\ComfyU\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\software\ComfyU\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\software\ComfyU\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DynamiCrafter\nodes.py", line 23, in run_inference
    image2video = Image2Video('./tmp/', resolution=resolution)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\software\ComfyU\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DynamiCrafter\scripts\gradio\i2v_test.py", line 32, in __init__
    model = instantiate_from_config(model_config)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\software\ComfyU\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DynamiCrafter\utils\utils.py", line 34, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\software\ComfyU\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts\..\..\custom_nodes\ComfyUI-DynamiCrafter\lvdm\models\ddpm3d.py", line 680, in __init__
    super().__init__(*args, **kwargs)
  File "K:\software\ComfyU\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts\..\..\custom_nodes\ComfyUI-DynamiCrafter\lvdm\models\ddpm3d.py", line 388, in __init__
    super().__init__(conditioning_key=conditioning_key, *args, **kwargs)
  File "K:\software\ComfyU\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts\..\..\custom_nodes\ComfyUI-DynamiCrafter\lvdm\models\ddpm3d.py", line 82, in __init__
    self.model = DiffusionWrapper(unet_config, conditioning_key)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\software\ComfyU\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts\..\..\custom_nodes\ComfyUI-DynamiCrafter\lvdm\models\ddpm3d.py", line 696, in __init__
    self.diffusion_model = instantiate_from_config(diff_model_config)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\software\ComfyU\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts\..\..\custom_nodes\ComfyUI-DynamiCrafter\utils\utils.py", line 34, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\software\ComfyU\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts\..\..\custom_nodes\ComfyUI-DynamiCrafter\utils\utils.py", line 42, in get_obj_from_str
    return getattr(importlib.import_module(module, package=None), cls)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "K:\software\ComfyU\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts\..\..\custom_nodes\ComfyUI-DynamiCrafter\lvdm\modules\networks\openaimodel3d.py", line 7, in <module>
    from lvdm.models.utils_diffusion import timestep_embedding
ModuleNotFoundError: No module named 'lvdm'

Prompt executed in 0.05 seconds
got prompt
[rgthree] Using rgthree's optimized recursive execution.
Prompt executor has been patched by Job Iterator!
2024-02-06 20:41:26,808 - mainlogger - INFO - LatentVisualDiffusion: Running in v-prediction mode
2024-02-06 20:41:26,818 - root - ERROR - !!! Exception during processing !!!
2024-02-06 20:41:26,819 - root - ERROR - Traceback (most recent call last):
  File "K:\software\ComfyU\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\software\ComfyU\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\software\ComfyU\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\software\ComfyU\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DynamiCrafter\nodes.py", line 23, in run_inference
    image2video = Image2Video('./tmp/', resolution=resolution)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\software\ComfyU\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DynamiCrafter\scripts\gradio\i2v_test.py", line 32, in __init__
    model = instantiate_from_config(model_config)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\software\ComfyU\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DynamiCrafter\utils\utils.py", line 34, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\software\ComfyU\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts\..\..\custom_nodes\ComfyUI-DynamiCrafter\lvdm\models\ddpm3d.py", line 680, in __init__
    super().__init__(*args, **kwargs)
  File "K:\software\ComfyU\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts\..\..\custom_nodes\ComfyUI-DynamiCrafter\lvdm\models\ddpm3d.py", line 388, in __init__
    super().__init__(conditioning_key=conditioning_key, *args, **kwargs)
  File "K:\software\ComfyU\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts\..\..\custom_nodes\ComfyUI-DynamiCrafter\lvdm\models\ddpm3d.py", line 82, in __init__
    self.model = DiffusionWrapper(unet_config, conditioning_key)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\software\ComfyU\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts\..\..\custom_nodes\ComfyUI-DynamiCrafter\lvdm\models\ddpm3d.py", line 696, in __init__
    self.diffusion_model = instantiate_from_config(diff_model_config)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\software\ComfyU\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts\..\..\custom_nodes\ComfyUI-DynamiCrafter\utils\utils.py", line 34, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\software\ComfyU\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts\..\..\custom_nodes\ComfyUI-DynamiCrafter\utils\utils.py", line 42, in get_obj_from_str
    return getattr(importlib.import_module(module, package=None), cls)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "K:\software\ComfyU\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts\..\..\custom_nodes\ComfyUI-DynamiCrafter\lvdm\modules\networks\openaimodel3d.py", line 7, in <module>
    from lvdm.models.utils_diffusion import timestep_embedding
ModuleNotFoundError: No module named 'lvdm'

**Comment by chaojie** [comment]
你太早clone了😓，重新git pull一下就好了 @zhaowtVincent

**Comment by CBRrrr** [comment]
有没有大佬帮我看一下这个 每次用WD14Tagger都无法加载模型，基本到个40%几就报错
-----------------------------------------------------------------------------------------------
Error occurred when executing WD14Tagger|pysssss:



File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger\wd14tagger.py", line 187, in tag
tags.append(wait_for_async(lambda: tag(image, model, threshold, character_threshold, exclude_tags, replace_underscore, trailing_comma)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger\pysssss.py", line 214, in wait_for_async
loop.run_until_complete(run_async())
File "asyncio\base_events.py", line 654, in run_until_complete
File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger\pysssss.py", line 204, in run_async
r = await async_fn()
^^^^^^^^^^^^^^^^
File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger\wd14tagger.py", line 54, in tag
await download_model(model_name, client_id, node)
File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger\wd14tagger.py", line 120, in download_model
await download_to_file(
File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger\pysssss.py", line 186, in download_to_file
async for chunk in response.content.iter_chunked(2048):
File "H:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\streams.py", line 44, in __anext__
rv = await self.read_func()
^^^^^^^^^^^^^^^^^^^^^^
File "H:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\streams.py", line 383, in read
await self._wait("read")
File "H:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\streams.py", line 301, in _wait
with self._timer:
File "H:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\helpers.py", line 735, in __exit__
raise asyncio.TimeoutError from None

**Comment by CBRrrr** [comment]
> ## 有没有大佬帮我看一下这个 每次用WD14Tagger都无法加载模型，基本到个40%几就报错
> Error occurred when executing WD14Tagger|pysssss:
> 
> File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute output_data, output_ui = get_output_data(obj, input_data_all) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list results.append(getattr(obj, func)(**slice_dict(input_data_all, i))) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger\wd14tagger.py", line 187, in tag tags.append(wait_for_async(lambda: tag(image, model, threshold, character_threshold, exclude_tags, replace_underscore, trailing_comma))) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger\pysssss.py", line 214, in wait_for_async loop.run_until_complete(run_async()) File "asyncio\base_events.py", line 654, in run_until_complete File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger\pysssss.py", line 204, in run_async r = await async_fn() ^^^^^^^^^^^^^^^^ File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger\wd14tagger.py", line 54, in tag await download_model(model_name, client_id, node) File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger\wd14tagger.py", line 120, in download_model await download_to_file( File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger\pysssss.py", line 186, in download_to_file async for chunk in response.content.iter_chunked(2048): File "H:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\streams.py", line 44, in **anext** rv = await self.read_func() ^^^^^^^^^^^^^^^^^^^^^^ File "H:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\streams.py", line 383, in read await self._wait("read") File "H:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\streams.py", line 301, in _wait with self._timer: File "H:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\helpers.py", line 735, in **exit** raise asyncio.TimeoutError from None

有没有办法单独下载tagger模型之类的 谢谢了！
