### ISSUE TITLE
Cannot import name _TORCH_GREATER_EQUAL_1_13

### ISSUE THREAD

**Issue by edwinzeng2005** [chaojie/ComfyUI-DynamiCrafter#10]
Here is the error:
Traceback (most recent call last):
  File "C:\tools\StabilityMatrix\Packages\ComfyUI\nodes.py", line 1888, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\tools\StabilityMatrix\Packages\ComfyUI\custom_nodes\ComfyUI-DynamiCrafter\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS
  File "C:\tools\StabilityMatrix\Packages\ComfyUI\custom_nodes\ComfyUI-DynamiCrafter\nodes.py", line 3, in <module>
    from .scripts.gradio.i2v_test import Image2Video
  File "C:\tools\StabilityMatrix\Packages\ComfyUI\custom_nodes\ComfyUI-DynamiCrafter\scripts\gradio\i2v_test.py", line 10, in <module>
    from pytorch_lightning import seed_everything
  File "C:\tools\StabilityMatrix\Packages\ComfyUI\venv\lib\site-packages\pytorch_lightning\__init__.py", line 27, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "C:\tools\StabilityMatrix\Packages\ComfyUI\venv\lib\site-packages\pytorch_lightning\callbacks\__init__.py", line 29, in <module>
    from pytorch_lightning.callbacks.pruning import ModelPruning
  File "C:\tools\StabilityMatrix\Packages\ComfyUI\venv\lib\site-packages\pytorch_lightning\callbacks\pruning.py", line 31, in <module>
    from pytorch_lightning.core.module import LightningModule
  File "C:\tools\StabilityMatrix\Packages\ComfyUI\venv\lib\site-packages\pytorch_lightning\core\__init__.py", line 16, in <module>
    from pytorch_lightning.core.module import LightningModule
  File "C:\tools\StabilityMatrix\Packages\ComfyUI\venv\lib\site-packages\pytorch_lightning\core\module.py", line 62, in <module>
    from pytorch_lightning.trainer import call
  File "C:\tools\StabilityMatrix\Packages\ComfyUI\venv\lib\site-packages\pytorch_lightning\trainer\__init__.py", line 17, in <module>
    from pytorch_lightning.trainer.trainer import Trainer
  File "C:\tools\StabilityMatrix\Packages\ComfyUI\venv\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 46, in <module>
    from pytorch_lightning.loops import _PredictionLoop, _TrainingEpochLoop
  File "C:\tools\StabilityMatrix\Packages\ComfyUI\venv\lib\site-packages\pytorch_lightning\loops\__init__.py", line 15, in <module>
    from pytorch_lightning.loops.evaluation_loop import _EvaluationLoop  # noqa: F401
  File "C:\tools\StabilityMatrix\Packages\ComfyUI\venv\lib\site-packages\pytorch_lightning\loops\evaluation_loop.py", line 29, in <module>
    from pytorch_lightning.loops.utilities import _no_grad_context, _select_data_fetcher, _verify_dataloader_idx_requirement
  File "C:\tools\StabilityMatrix\Packages\ComfyUI\venv\lib\site-packages\pytorch_lightning\loops\utilities.py", line 24, in <module>
    from lightning_fabric.utilities.imports import _TORCH_EQUAL_2_0, _TORCH_GREATER_EQUAL_1_13
ImportError: cannot import name '_TORCH_GREATER_EQUAL_1_13' from 'lightning_fabric.utilities.imports' (C:\tools\StabilityMatrix\Packages\ComfyUI\venv\lib\site-packages\lightning_fabric\utilities\imports.py)

Not sure how to resolve it.

**Comment by doogyhatts** [comment]
Resolved the error by installing python_lightning separately in the ComfyUI manager.
I will use the fork from Kijai instead.
