### ISSUE TITLE
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

### ISSUE THREAD

**Issue by BasicNP** [chaojie/ComfyUI-DynamiCrafter#12]
im getting this PytorchStreamReader error on multiple models. Can anybody help with this?

Traceback (most recent call last):
  File "E:\comfy inter\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\comfy inter\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\comfy inter\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\comfy inter\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DynamiCrafter\nodes.py", line 26, in run_inference
    image2video = Image2VideoInterp('./tmp/', resolution=resolution,frame_length=frame_length)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\comfy inter\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DynamiCrafter\scripts\gradio\i2v_test_application.py", line 33, in __init__
    model = instantiate_from_config(model_config)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\comfy inter\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DynamiCrafter\utils\utils.py", line 34, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\comfy inter\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DynamiCrafter\lvdm\models\ddpm3d.py", line 680, in __init__
    super().__init__(*args, **kwargs)
  File "E:\comfy inter\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DynamiCrafter\lvdm\models\ddpm3d.py", line 414, in __init__
    self.instantiate_cond_stage(cond_stage_config)
  File "E:\comfy inter\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DynamiCrafter\lvdm\models\ddpm3d.py", line 447, in instantiate_cond_stage
    model = instantiate_from_config(config)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\comfy inter\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DynamiCrafter\utils\utils.py", line 34, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\comfy inter\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DynamiCrafter\lvdm\modules\encoders\condition.py", line 188, in __init__
    model, _, _ = open_clip.create_model_and_transforms(arch, device=torch.device('cpu'), pretrained=version)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\comfy inter\ComfyUI_windows_portable\python_embeded\Lib\site-packages\open_clip\factory.py", line 324, in create_model_and_transforms
    model = create_model(
            ^^^^^^^^^^^^^
  File "E:\comfy inter\ComfyUI_windows_portable\python_embeded\Lib\site-packages\open_clip\factory.py", line 237, in create_model
    load_checkpoint(model, checkpoint_path)
  File "E:\comfy inter\ComfyUI_windows_portable\python_embeded\Lib\site-packages\open_clip\factory.py", line 103, in load_checkpoint
    state_dict = load_state_dict(checkpoint_path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\comfy inter\ComfyUI_windows_portable\python_embeded\Lib\site-packages\open_clip\factory.py", line 88, in load_state_dict
    checkpoint = torch.load(checkpoint_path, map_location=map_location)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\comfy inter\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\serialization.py", line 993, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\comfy inter\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\serialization.py", line 447, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

**Comment by zixian-wu** [comment]
I'm experiencing the same Issue.

**Comment by siliconx** [comment]
the same
